name: Build and Deploy Qt Application on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Qt
        run: |
          choco install qt5-sdk
          setx /M PATH "C:\Qt\5.15.2\msvc2019_64\bin;%PATH%"
        shell: bash

      - name: Build Qt application
        run: |
          qmake CONFIG+=release
          nmake
        shell: cmd

      - name: Deploy Qt application
        run: |
          windeployqt .\release\<your-application>.exe
          mkdir dist
          xcopy .\release dist /s /e /y
        shell: cmd

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-qt-app
          path: dist
       
